// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHaN5uQU4gC9Cs0C7YxY9xzRb2qDN_jw8',
    appId: '1:182522841200:web:026ea99494ab17d789ccb5',
    messagingSenderId: '182522841200',
    projectId: 'stock-t20',
    authDomain: 'stock-t20.firebaseapp.com',
    storageBucket: 'stock-t20.firebasestorage.app',
    measurementId: 'G-JLXSHP2MTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB95EKAf7v8GDanTL6hdRpAb51vG0jNADk',
    appId: '1:182522841200:android:eb390b4c12524c9489ccb5',
    messagingSenderId: '182522841200',
    projectId: 'stock-t20',
    storageBucket: 'stock-t20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuofPv_xwww9_bCOBshWv68l2xDGu8aA8',
    appId: '1:182522841200:ios:aec05d880fc0a31a89ccb5',
    messagingSenderId: '182522841200',
    projectId: 'stock-t20',
    storageBucket: 'stock-t20.firebasestorage.app',
    iosBundleId: 'com.example.yaaara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuofPv_xwww9_bCOBshWv68l2xDGu8aA8',
    appId: '1:182522841200:ios:aec05d880fc0a31a89ccb5',
    messagingSenderId: '182522841200',
    projectId: 'stock-t20',
    storageBucket: 'stock-t20.firebasestorage.app',
    iosBundleId: 'com.example.yaaara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHaN5uQU4gC9Cs0C7YxY9xzRb2qDN_jw8',
    appId: '1:182522841200:web:5e853c426c8162bc89ccb5',
    messagingSenderId: '182522841200',
    projectId: 'stock-t20',
    authDomain: 'stock-t20.firebaseapp.com',
    storageBucket: 'stock-t20.firebasestorage.app',
    measurementId: 'G-LXRL7XZ08G',
  );
}
